# Generated by Django 5.2.4 on 2025-08-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='what_learned',
            field=models.TextField(blank=True, null=True, verbose_name='Что я изучил нового'),
        ),
        migrations.AddField(
            model_name='note',
            name='what_not_understood',
            field=models.TextField(blank=True, null=True, verbose_name='Что непонятно'),
        ),
    ]
