# Generated by Django 5.2.4 on 2025-08-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_what_learned_note_what_not_understood'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.CharField(choices=[('IT', 'IT'), ('Languages', 'Языки')], default='IT', max_length=20, verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='subcategory',
            field=models.CharField(choices=[('Web Dev', 'Веб-разработка'), ('Cybersecurity', 'Компьютерная безопасность'), ('Networks', 'Компьютерные сети'), ('Python', 'Python'), ('C++', 'C++'), ('English', 'Английский'), ('Korean', 'Корейский'), ('Japane', 'Японский')], default='IT', max_length=50, verbose_name='Подкатегория'),
            preserve_default=False,
        ),
    ]
